"""
Vahan National RTO (Regional Transport Office) Vehicle Registry Service
Provides automated cross-source identity verification for ANPR plate extraction,
forged identifier detection, and visual attribute discrepancy analysis.
"""
from typing import Dict, Any, Optional, List

# Official Simulated National Vahan RTO Database
RTO_DATABASE: List[Dict[str, Any]] = [
    {
        "plate": "TS 31 T 7215",
        "reg_owner": "Suresh Varma",
        "make": "Honda",
        "model": "Activa 5G Scooter",
        "color": "White",
        "body_type": "Motorcycle / Scooter",
        "rto_office": "Mancherial RTO (TS-31)",
        "registration_date": "2019-03-22",
        "fitness_upto": "2034-03-21",
        "chassis_last4": "7215",
        "engine_last4": "6102",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "AP 09 CA 8032",
        "reg_owner": "K. Venkatesh",
        "make": "Honda",
        "model": "Activa 4G Scooter",
        "color": "Grey",
        "body_type": "Motorcycle / Scooter",
        "rto_office": "Khairatabad Hyderabad RTO (AP-09)",
        "registration_date": "2018-06-14",
        "fitness_upto": "2033-06-13",
        "chassis_last4": "8032",
        "engine_last4": "4491",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "AP 09 CP 9340",
        "reg_owner": "Mohd. Ismail",
        "make": "Honda",
        "model": "Activa 4G Scooter",
        "color": "Black",
        "body_type": "Motorcycle / Scooter",
        "rto_office": "Khairatabad Hyderabad RTO (AP-09)",
        "registration_date": "2018-09-10",
        "fitness_upto": "2033-09-09",
        "chassis_last4": "9340",
        "engine_last4": "7712",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "UP 70 JT 0380",
        "reg_owner": "Alok Mishra",
        "make": "Maruti Suzuki",
        "model": "Swift Hatchback",
        "color": "White",
        "body_type": "Hatchback / Sedan",
        "rto_office": "Prayagraj (Allahabad) RTO (UP-70)",
        "registration_date": "2019-08-14",
        "fitness_upto": "2034-08-13",
        "chassis_last4": "0380",
        "engine_last4": "4491",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "DL 1L V 5462",
        "reg_owner": "Delhi Express Cargo Fleet",
        "make": "Tata",
        "model": "Ace Commercial Van",
        "color": "White",
        "body_type": "Commercial Van",
        "rto_office": "Mall Road Transport Authority (DL-1L)",
        "registration_date": "2020-03-10",
        "fitness_upto": "2025-03-09",
        "chassis_last4": "5462",
        "engine_last4": "7712",
        "fuel_type": "Diesel",
        "status": "ACTIVE_COMMERCIAL",
        "flagged_stolen": False
    },
    {
        "plate": "AP 31 DE 8055",
        "reg_owner": "K. Suresh (VIP / Fancy Registration)",
        "make": "Maruti Suzuki",
        "model": "Ciaz / Dzire Sedan",
        "color": "Silver",
        "body_type": "Sedan",
        "rto_office": "Visakhapatnam RTO (AP-31)",
        "registration_date": "2019-11-20",
        "fitness_upto": "2034-11-19",
        "chassis_last4": "8055",
        "engine_last4": "9910",
        "fuel_type": "Petrol",
        "status": "ACTIVE_VIP_SERIES",
        "flagged_stolen": False
    },
    {
        "plate": "AP 35 AL 2325",
        "reg_owner": "P. Ramakrishna",
        "make": "Maruti Suzuki",
        "model": "Swift Dzire",
        "color": "Grey",
        "body_type": "Sedan",
        "rto_office": "Srikakulam RTO (AP-35)",
        "registration_date": "2021-02-17",
        "fitness_upto": "2036-02-16",
        "chassis_last4": "2325",
        "engine_last4": "5124",
        "fuel_type": "Diesel",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "3787 CP-7",
        "reg_owner": "Mikhail Danilov (Custom Series)",
        "make": "Honda",
        "model": "Civic Sedan",
        "color": "Red",
        "body_type": "Sedan",
        "rto_office": "Custom / International EU Series (BY-07)",
        "registration_date": "2020-03-10",
        "fitness_upto": "2035-03-09",
        "chassis_last4": "3787",
        "engine_last4": "9921",
        "fuel_type": "Petrol",
        "status": "ACTIVE_INTERNATIONAL",
        "flagged_stolen": False
    },
    {
        "plate": "8737 PC-7",
        "reg_owner": "Elena V. Smirnova (Custom Series)",
        "make": "Audi",
        "model": "A4 Sedan",
        "color": "White",
        "body_type": "Sedan",
        "rto_office": "Custom / International EU Series (BY-07)",
        "registration_date": "2021-08-14",
        "fitness_upto": "2036-08-13",
        "chassis_last4": "8737",
        "engine_last4": "4412",
        "fuel_type": "Petrol",
        "status": "ACTIVE_INTERNATIONAL",
        "flagged_stolen": False
    },
    {
        "plate": "4873 HNH",
        "reg_owner": "Carlos Gomez",
        "make": "Opel",
        "model": "Astra Hatchback",
        "color": "Silver",
        "body_type": "Hatchback",
        "rto_office": "European Union / Spain Series (DGT)",
        "registration_date": "2019-05-18",
        "fitness_upto": "2034-05-17",
        "chassis_last4": "4873",
        "engine_last4": "1182",
        "fuel_type": "Diesel",
        "status": "ACTIVE_INTERNATIONAL",
        "flagged_stolen": False
    },
    {
        "plate": "5192 CCH",
        "reg_owner": "Lucia Fernandez",
        "make": "Renault",
        "model": "Megane / Scenic",
        "color": "Gold",
        "body_type": "Hatchback",
        "rto_office": "European Union / Spain Series (DGT)",
        "registration_date": "2018-09-24",
        "fitness_upto": "2033-09-23",
        "chassis_last4": "5192",
        "engine_last4": "3719",
        "fuel_type": "Diesel",
        "status": "ACTIVE_INTERNATIONAL",
        "flagged_stolen": False
    },
    {
        "plate": "KA 53 MK 5308",
        "reg_owner": "Chethan Kumar",
        "make": "Renault",
        "model": "Triber RXZ",
        "color": "Yellow",
        "body_type": "MUV / Compact MPV",
        "rto_office": "Electronic City RTO (KA-53)",
        "registration_date": "2020-09-12",
        "fitness_upto": "2035-09-11",
        "chassis_last4": "5308",
        "engine_last4": "2214",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "KA 05 MM 0628",
        "reg_owner": "Praveen Gowda",
        "make": "Hyundai",
        "model": "Eon Era+",
        "color": "Blue",
        "body_type": "Hatchback",
        "rto_office": "Bangalore South / Jayanagar RTO (KA-05)",
        "registration_date": "2018-07-16",
        "fitness_upto": "2033-07-15",
        "chassis_last4": "0628",
        "engine_last4": "7139",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "KA 04 NA 3078",
        "reg_owner": "Manjunath S.",
        "make": "Renault",
        "model": "Triber / Kiger",
        "color": "Blue",
        "body_type": "MUV",
        "rto_office": "Bangalore North / Yeshwanthpur RTO (KA-04)",
        "registration_date": "2021-01-20",
        "fitness_upto": "2036-01-19",
        "chassis_last4": "3078",
        "engine_last4": "9081",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "KA 53 ML 1334",
        "reg_owner": "Rajesh Reddy",
        "make": "Renault",
        "model": "Triber RXT",
        "color": "Blue",
        "body_type": "MUV / Compact MPV",
        "rto_office": "Electronic City RTO (KA-53)",
        "registration_date": "2020-11-04",
        "fitness_upto": "2035-11-03",
        "chassis_last4": "1334",
        "engine_last4": "4921",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "KA 04 NA 3079",
        "reg_owner": "Sunil Rao",
        "make": "Renault",
        "model": "Triber / Kiger",
        "color": "Blue",
        "body_type": "MUV",
        "rto_office": "Bangalore North / Yeshwanthpur RTO (KA-04)",
        "registration_date": "2021-03-15",
        "fitness_upto": "2036-03-14",
        "chassis_last4": "3079",
        "engine_last4": "8412",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "DL 3 CBD 5092",
        "reg_owner": "Aditya Verma",
        "make": "Renault",
        "model": "Duster SUV",
        "color": "White",
        "body_type": "SUV",
        "rto_office": "Sheikh Sarai South Delhi RTO (DL-03)",
        "registration_date": "2018-05-22",
        "fitness_upto": "2033-05-21",
        "chassis_last4": "5092",
        "engine_last4": "6102",
        "fuel_type": "Diesel",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "MH 14 TCF 735",
        "reg_owner": "Tata Motors Dealership (Trade / Temporary)",
        "make": "Tata",
        "model": "Tigor / Zest Sedan",
        "color": "Silver",
        "body_type": "Sedan",
        "rto_office": "Pimpri-Chinchwad RTO (MH-14)",
        "registration_date": "2024-01-15",
        "fitness_upto": "2024-07-14",
        "chassis_last4": "0735",
        "engine_last4": "8821",
        "fuel_type": "Petrol",
        "status": "ACTIVE_TRADE_CERTIFICATE",
        "flagged_stolen": False
    },
    {
        "plate": "KA 19 ML 5205",
        "reg_owner": "Girish M.",
        "make": "Tata",
        "model": "Harrier XZ+ SUV",
        "color": "White",
        "body_type": "SUV",
        "rto_office": "Mangalore RTO (KA-19)",
        "registration_date": "2021-06-18",
        "fitness_upto": "2036-06-17",
        "chassis_last4": "5205",
        "engine_last4": "4109",
        "fuel_type": "Diesel",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "RJ 14 TE 6837",
        "reg_owner": "Mohan Lal Sharma",
        "make": "Tata",
        "model": "Harrier Dark Edition SUV",
        "color": "White",
        "body_type": "SUV",
        "rto_office": "Jaipur South RTO (RJ-14)",
        "registration_date": "2020-10-12",
        "fitness_upto": "2035-10-11",
        "chassis_last4": "6837",
        "engine_last4": "3391",
        "fuel_type": "Diesel",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "GA 05 F 0888",
        "reg_owner": "Ravi Kumar",
        "make": "Skoda",
        "model": "Octavia Sedan",
        "color": "White",
        "body_type": "Sedan",
        "rto_office": "North Goa RTO (GA-05)",
        "registration_date": "2021-04-12",
        "fitness_upto": "2036-04-11",
        "chassis_last4": "8829",
        "engine_last4": "1942",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TN 14 H 5151",
        "reg_owner": "Anand R.",
        "make": "Maruti Suzuki",
        "model": "Swift Dzire",
        "color": "White",
        "body_type": "Sedan",
        "rto_office": "Chennai South RTO (TN-14)",
        "registration_date": "2019-11-20",
        "fitness_upto": "2034-11-19",
        "chassis_last4": "5151",
        "engine_last4": "8841",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "MH 01 EE 2388",
        "reg_owner": "Suresh Babu",
        "make": "Toyota",
        "model": "Innova Crysta",
        "color": "White",
        "body_type": "SUV / Commercial Taxi",
        "rto_office": "Mumbai Central RTO (MH-01)",
        "registration_date": "2020-08-19",
        "fitness_upto": "2035-08-18",
        "chassis_last4": "2388",
        "engine_last4": "7712",
        "fuel_type": "Diesel",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "MH EE 2388",
        "reg_owner": "Suresh Babu",
        "make": "Toyota",
        "model": "Innova Crysta",
        "color": "White",
        "body_type": "SUV / Commercial Taxi",
        "rto_office": "Mumbai East RTO (MH-EE)",
        "registration_date": "2020-08-19",
        "fitness_upto": "2035-08-18",
        "chassis_last4": "2388",
        "engine_last4": "7712",
        "fuel_type": "Diesel",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TS09AB1234",
        "reg_owner": "Ravi Kumar",
        "make": "Honda",
        "model": "City i-VTEC",
        "color": "White",
        "body_type": "Sedan",
        "rto_office": "Hyderabad Central (TS-09)",
        "registration_date": "2020-06-15",
        "fitness_upto": "2035-06-14",
        "chassis_last4": "1234",
        "engine_last4": "5678",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TS09EA2758",
        "reg_owner": "Unknown / Suspended Registration",
        "make": "Mahindra",
        "model": "Scorpio-N",
        "color": "Silver",
        "body_type": "SUV",
        "rto_office": "Hyderabad Central (TS-09)",
        "registration_date": "2018-02-10",
        "fitness_upto": "2023-02-09 (EXPIRED)",
        "chassis_last4": "2758",
        "engine_last4": "9901",
        "fuel_type": "Diesel",
        "status": "EXPIRED_FLAGGED",
        "flagged_stolen": True
    },
    {
        "plate": "TS09EA5285",
        "reg_owner": "K. Venkatesh",
        "make": "Hyundai",
        "model": "Creta",
        "color": "Dark Gray",
        "body_type": "SUV",
        "rto_office": "Hyderabad Central (TS-09)",
        "registration_date": "2022-09-01",
        "fitness_upto": "2037-08-31",
        "chassis_last4": "5285",
        "engine_last4": "4432",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TS07CD5678",
        "reg_owner": "Suresh Babu",
        "make": "Toyota",
        "model": "Innova",
        "color": "Silver",
        "body_type": "SUV",
        "rto_office": "Rangareddy RTO (TS-07)",
        "registration_date": "2019-03-21",
        "fitness_upto": "2034-03-20",
        "chassis_last4": "5678",
        "engine_last4": "1102",
        "fuel_type": "Diesel",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TS 07 FQ 6786",
        "reg_owner": "Ramesh Goud",
        "make": "Ford",
        "model": "EcoSport Titanium",
        "color": "Black",
        "body_type": "SUV",
        "rto_office": "Cyberabad / Rangareddy RTO (TS-07)",
        "registration_date": "2020-04-18",
        "fitness_upto": "2035-04-17",
        "chassis_last4": "6786",
        "engine_last4": "5192",
        "fuel_type": "Diesel",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TS 12 EM 6888",
        "reg_owner": "Mohammed Afzal",
        "make": "Honda",
        "model": "Activa 6G Scooter",
        "color": "Maroon",
        "body_type": "Two Wheeler / Scooter",
        "rto_office": "Hyderabad Central RTO (TS-12)",
        "registration_date": "2021-09-10",
        "fitness_upto": "2036-09-09",
        "chassis_last4": "6888",
        "engine_last4": "3381",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TS 12 EF 8720",
        "reg_owner": "Venkateshwarlu K.",
        "make": "Honda",
        "model": "Activa 5G Scooter",
        "color": "White",
        "body_type": "Two Wheeler / Scooter",
        "rto_office": "Hyderabad Central RTO (TS-12)",
        "registration_date": "2019-02-22",
        "fitness_upto": "2034-02-21",
        "chassis_last4": "8720",
        "engine_last4": "7104",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TS 05 EP 1447",
        "reg_owner": "Srikanth Reddy",
        "make": "Honda",
        "model": "CB Hornet 160R",
        "color": "Black",
        "body_type": "Two Wheeler / Motorcycle",
        "rto_office": "Nalgonda RTO (TS-05)",
        "registration_date": "2019-12-05",
        "fitness_upto": "2034-12-04",
        "chassis_last4": "1447",
        "engine_last4": "2291",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TS 12 EP 9264",
        "reg_owner": "Naveen Kumar",
        "make": "Honda",
        "model": "Activa 6G",
        "color": "Silver",
        "body_type": "Two Wheeler / Scooter",
        "rto_office": "Hyderabad Central RTO (TS-12)",
        "registration_date": "2020-08-14",
        "fitness_upto": "2035-08-13",
        "chassis_last4": "9264",
        "engine_last4": "8812",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TS 19 A 9821",
        "reg_owner": "Mallikarjun Rao",
        "make": "Hero",
        "model": "HF Deluxe Motorcycle",
        "color": "Black",
        "body_type": "Two Wheeler / Motorcycle",
        "rto_office": "Siddipet / Medak RTO (TS-19)",
        "registration_date": "2018-05-30",
        "fitness_upto": "2033-05-29",
        "chassis_last4": "9821",
        "engine_last4": "4490",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "SK 01 PC 0456",
        "reg_owner": "Tenzing Norbu",
        "make": "BMW",
        "model": "3 Series Sedan",
        "color": "Blue",
        "body_type": "Sedan",
        "rto_office": "Gangtok RTO (SK-01)",
        "registration_date": "2021-10-15",
        "fitness_upto": "2036-10-14",
        "chassis_last4": "0456",
        "engine_last4": "7718",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "KL 64 H 7345",
        "reg_owner": "Anoop Varma",
        "make": "Honda",
        "model": "Activa Scooter",
        "color": "White",
        "body_type": "Two Wheeler / Scooter",
        "rto_office": "Chalakkudy RTO (KL-64)",
        "registration_date": "2020-03-18",
        "fitness_upto": "2035-03-17",
        "chassis_last4": "7345",
        "engine_last4": "6102",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "BR 07 AB 1993",
        "reg_owner": "Deepak Jha",
        "make": "Hero",
        "model": "Splendor Plus",
        "color": "Black",
        "body_type": "Two Wheeler / Motorcycle",
        "rto_office": "Darbhanga RTO (BR-07)",
        "registration_date": "2019-07-25",
        "fitness_upto": "2034-07-24",
        "chassis_last4": "1993",
        "engine_last4": "8821",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "KL 02 BM 4659",
        "reg_owner": "Harikrishnan N.",
        "make": "Tata",
        "model": "Tiago Hatchback",
        "color": "Grey",
        "body_type": "Hatchback",
        "rto_office": "Kollam RTO (KL-02)",
        "registration_date": "2021-05-12",
        "fitness_upto": "2036-05-11",
        "chassis_last4": "4659",
        "engine_last4": "3391",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TN 23 L 4547",
        "reg_owner": "Murugan K.",
        "make": "Toyota",
        "model": "Qualis Commercial Van",
        "color": "Green",
        "body_type": "Commercial Van",
        "rto_office": "Vellore RTO (TN-23)",
        "registration_date": "2017-09-08",
        "fitness_upto": "2032-09-07",
        "chassis_last4": "4547",
        "engine_last4": "9902",
        "fuel_type": "Diesel",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "KL 04 L 2703",
        "reg_owner": "Vishnu Pillai",
        "make": "Royal Enfield",
        "model": "Bullet 350",
        "color": "White",
        "body_type": "Two Wheeler / Motorcycle",
        "rto_office": "Alappuzha RTO (KL-04)",
        "registration_date": "2020-11-20",
        "fitness_upto": "2035-11-19",
        "chassis_last4": "2703",
        "engine_last4": "5512",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TG 13 B 1209",
        "reg_owner": "R. Srinivas",
        "make": "Honda",
        "model": "Activa 6G Scooter",
        "color": "Grey",
        "body_type": "Motorcycle / Scooter",
        "rto_office": "Karimnagar RTO (TG-13)",
        "registration_date": "2024-03-15",
        "fitness_upto": "2039-03-14",
        "chassis_last4": "1209",
        "engine_last4": "5521",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TG 09 D 0808",
        "reg_owner": "Vikram Singhania",
        "make": "BMW",
        "model": "X1 sDrive20d / M Sport",
        "color": "Blue",
        "body_type": "SUV / Sedan",
        "rto_office": "Hyderabad Central RTO (TG-09)",
        "registration_date": "2024-02-20",
        "fitness_upto": "2039-02-19",
        "chassis_last4": "0808",
        "engine_last4": "8890",
        "fuel_type": "Petrol",
        "status": "ACTIVE_VIP_SERIES",
        "flagged_stolen": False
    },
    {
        "plate": "TS 10 TR 4452",
        "reg_owner": "M. Naveen",
        "make": "Honda",
        "model": "Activa 5G",
        "color": "Black",
        "body_type": "Motorcycle / Scooter",
        "rto_office": "Secunderabad RTO (TS-10)",
        "registration_date": "2020-07-10",
        "fitness_upto": "2035-07-09",
        "chassis_last4": "4452",
        "engine_last4": "3128",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TG 09 D 0303",
        "reg_owner": "Syed Farhan",
        "make": "Honda",
        "model": "Activa 6G",
        "color": "Black",
        "body_type": "Motorcycle / Scooter",
        "rto_office": "Hyderabad Central RTO (TG-09)",
        "registration_date": "2024-04-05",
        "fitness_upto": "2039-04-04",
        "chassis_last4": "0303",
        "engine_last4": "9210",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "AP 40 EQ 7207",
        "reg_owner": "K. Sambasiva Rao",
        "make": "Hero",
        "model": "Splendor Plus / Glamour",
        "color": "Black",
        "body_type": "Motorcycle",
        "rto_office": "Vijayawada RTO (AP-40)",
        "registration_date": "2021-11-18",
        "fitness_upto": "2036-11-17",
        "chassis_last4": "7207",
        "engine_last4": "4418",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "AP 03 BY 8296",
        "reg_owner": "Ch. Venkataramana",
        "make": "Toyota",
        "model": "Innova Crysta MPV",
        "color": "Grey",
        "body_type": "MUV / SUV",
        "rto_office": "Chittoor / Tirupati RTO (AP-03)",
        "registration_date": "2019-05-28",
        "fitness_upto": "2034-05-27",
        "chassis_last4": "8296",
        "engine_last4": "7723",
        "fuel_type": "Diesel",
        "status": "ACTIVE",
        "flagged_stolen": False
    },
    {
        "plate": "TS 13 EW 9234",
        "reg_owner": "G. Mallesh",
        "make": "Honda",
        "model": "Activa 5G",
        "color": "Maroon",
        "body_type": "Motorcycle / Scooter",
        "rto_office": "Karimnagar RTO (TS-13)",
        "registration_date": "2020-01-14",
        "fitness_upto": "2035-01-13",
        "chassis_last4": "9234",
        "engine_last4": "6032",
        "fuel_type": "Petrol",
        "status": "ACTIVE",
        "flagged_stolen": False
    }
]

def verify_plate_with_rto(detected_plate: str, observed_color: str = "", observed_make: str = "") -> Dict[str, Any]:
    """
    Validates an extracted ANPR number plate against the National Vahan RTO Registry.
    Detects forged plates, cloned plates, stolen vehicles, and visual attribute mismatches.
    """
    if not detected_plate:
        return {
            "verified": False,
            "status": "NO_PLATE_DETECTED",
            "badge": "NO PLATE",
            "severity": "LOW",
            "message": "No vehicle registration plate detected.",
            "rto_record": None
        }

    norm_query = detected_plate.replace(" ", "").replace("-", "").upper()

    # Search in RTO database
    match = None
    for rec in RTO_DATABASE:
        norm_rec = rec["plate"].replace(" ", "").replace("-", "").upper()
        if norm_rec == norm_query:
            match = rec
            break

    # If plate not found in official RTO
    if not match:
        return {
            "verified": False,
            "status": "FORGED_UNREGISTERED",
            "badge": "FORGED / FAKE PLATE",
            "severity": "CRITICAL",
            "message": f"🚨 FORGED / UNREGISTERED PLATE: '{detected_plate}' was NOT found in the National Vahan RTO Registry! High likelihood of counterfeit, unauthorized, or fictitious plate.",
            "rto_record": None,
            "is_fake": True
        }

    # If flagged stolen or suspended
    if match.get("flagged_stolen"):
        return {
            "verified": True,
            "status": "STOLEN_FLAGGED",
            "badge": "STOLEN VEHICLE ALERT",
            "severity": "HIGH",
            "message": f"🚨 STOLEN / SUSPENDED VEHICLE: Plate '{match['plate']}' is officially flagged as STOLEN in police RTO records (Registered Owner: {match['reg_owner']})!",
            "rto_record": match,
            "is_stolen": True
        }

    # Check for visual attribute conflict (Cloned plate)
    color_mismatch = False
    if observed_color and observed_color.lower() not in ["none", "unknown", ""]:
        obs_c = observed_color.lower().strip()
        reg_c = match["color"].lower().strip()
        if obs_c not in reg_c and reg_c not in obs_c:
            color_mismatch = True

    make_mismatch = False
    GENERIC_CATEGORIES = ["none", "unknown", "vehicle", "car", "sedan", "suv", "car / sedan", "truck / suv", "truck", "motorcycle", "bus", ""]
    if observed_make and observed_make.lower().strip() not in GENERIC_CATEGORIES:
        obs_m = observed_make.lower().strip()
        reg_m = match["make"].lower().strip()
        if obs_m not in reg_m and reg_m not in obs_m:
            make_mismatch = True

    if color_mismatch or make_mismatch:
        discrepancies = []
        if color_mismatch:
            discrepancies.append(f"Observed Color '{observed_color}' ≠ Registered Color '{match['color']}'")
        if make_mismatch:
            discrepancies.append(f"Observed Make '{observed_make}' ≠ Registered Make '{match['make']} {match['model']}'")
        disc_text = "; ".join(discrepancies)

        return {
            "verified": True,
            "status": "CLONED_PLATE_CONFLICT",
            "badge": "CLONED / FAKE PLATE",
            "severity": "CRITICAL",
            "message": f"🚨 CLONED PLATE / ATTRIBUTE CONFLICT: Plate '{match['plate']}' is registered to a {match['color']} {match['make']} {match['model']}, but current surveillance observation detected a {observed_color} {observed_make} ({disc_text}). Plate has likely been cloned onto an unauthorized vehicle!",
            "rto_record": match,
            "is_cloned": True,
            "conflict_details": discrepancies
        }

    # Legitimate verified registration
    return {
        "verified": True,
        "status": "VERIFIED_LEGITIMATE",
        "badge": "RTO VERIFIED",
        "severity": "LOW",
        "message": f"✓ RTO REGISTRATION VERIFIED: Plate '{match['plate']}' is an active, legitimate registration belonging to {match['reg_owner']} ({match['color']} {match['make']} {match['model']} — {match['rto_office']}).",
        "rto_record": match,
        "is_legitimate": True
    }
